#!/usr/bin/env bash

date=$(exec date -u +%Y-%m-%d)
filename=posts/$date.md

header="---
title: $@
author: Shana
keywords: [no, nothing]
date: ${date}
---
"

echo "$header" >> $filename
vim $filename
