#!/usr/bin/env bash

if [[ $# -eq 0 ]]; then
  echo "Error: you didn't include a title"
  echo "Usage: $0 <title>"
  exit 1
fi

date=$(exec date -u +%Y-%m-%d)
filename="posts/"

# this is broken for some reason :(
for w in "${@,,}"; do
  filename+="${w}-" 
done

filename="${filename%*-}.md"

header="---
title: $@
author: Shana
keywords: [no, nothing]
date: ${date}
---
"

echo "$header" >> $filename
vim $filename
